language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
  - DEPS=lowest
  - DEPS=latest

before_script:
  - composer self-update
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable --no-interaction ; fi
  - travis_retry composer install --no-interaction

script:
  - composer test

matrix:
  fast_finish: true
