language: php

php:
  - 5.6
  - 7
  - 7.1
  - 7.2

env:
  - DEPS=lowest
  - DEPS=latest

before_script:
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-stable --no-interaction --prefer-lowest ; fi
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update --prefer-stable --no-interaction ; fi

script:
  - composer test

matrix:
  fast_finish: true
